/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminpanelRouteImport } from './routes/adminpanel'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BlogDetailsRouteImport } from './routes/blog-details'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectDetailsRouteImport } from './routes/project-details'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeamDetailsRouteImport } from './routes/team-details'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminpanelIndexRouteImport } from './routes/adminpanel.index'
import { Route as AdminpanelBlogRouteImport } from './routes/adminpanel.blog'
import { Route as AdminpanelProjectsRouteImport } from './routes/adminpanel.projects'
import { Route as AdminpanelTeamRouteImport } from './routes/adminpanel.team'
import { Route as BlogDetailsIdRouteImport } from './routes/blog-details.$id'
import { Route as TeamDetailsIdRouteImport } from './routes/team-details.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpanelRoute = AdminpanelRouteImport.update({
  id: '/adminpanel',
  path: '/adminpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDetailsRoute = BlogDetailsRouteImport.update({
  id: '/blog-details',
  path: '/blog-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDetailsRoute = ProjectDetailsRouteImport.update({
  id: '/project-details',
  path: '/project-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamDetailsRoute = TeamDetailsRouteImport.update({
  id: '/team-details',
  path: '/team-details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminpanelIndexRoute = AdminpanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelBlogRoute = AdminpanelBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelProjectsRoute = AdminpanelProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminpanelRoute,
} as any)
const AdminpanelTeamRoute = AdminpanelTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminpanelRoute,
} as any)
const BlogDetailsIdRoute = BlogDetailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogDetailsRoute,
} as any)
const TeamDetailsIdRoute = TeamDetailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamDetailsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/adminpanel': typeof AdminpanelRouteWithChildren
  '/blog': typeof BlogRoute
  '/blog-details': typeof BlogDetailsRouteWithChildren
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/project-details': typeof ProjectDetailsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/team-details': typeof TeamDetailsRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/adminpanel/blog': typeof AdminpanelBlogRoute
  '/adminpanel/projects': typeof AdminpanelProjectsRoute
  '/adminpanel/team': typeof AdminpanelTeamRoute
  '/blog-details/$id': typeof BlogDetailsIdRoute
  '/team-details/$id': typeof TeamDetailsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/adminpanel/': typeof AdminpanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/blog-details': typeof BlogDetailsRouteWithChildren
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/project-details': typeof ProjectDetailsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/team-details': typeof TeamDetailsRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/adminpanel/blog': typeof AdminpanelBlogRoute
  '/adminpanel/projects': typeof AdminpanelProjectsRoute
  '/adminpanel/team': typeof AdminpanelTeamRoute
  '/blog-details/$id': typeof BlogDetailsIdRoute
  '/team-details/$id': typeof TeamDetailsIdRoute
  '/admin': typeof AdminIndexRoute
  '/adminpanel': typeof AdminpanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/adminpanel': typeof AdminpanelRouteWithChildren
  '/blog': typeof BlogRoute
  '/blog-details': typeof BlogDetailsRouteWithChildren
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/project-details': typeof ProjectDetailsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/team-details': typeof TeamDetailsRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/adminpanel/blog': typeof AdminpanelBlogRoute
  '/adminpanel/projects': typeof AdminpanelProjectsRoute
  '/adminpanel/team': typeof AdminpanelTeamRoute
  '/blog-details/$id': typeof BlogDetailsIdRoute
  '/team-details/$id': typeof TeamDetailsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/adminpanel/': typeof AdminpanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/adminpanel'
    | '/blog'
    | '/blog-details'
    | '/contact'
    | '/license'
    | '/login'
    | '/project-details'
    | '/projects'
    | '/services'
    | '/team'
    | '/team-details'
    | '/admin/blog'
    | '/admin/projects'
    | '/admin/team'
    | '/adminpanel/blog'
    | '/adminpanel/projects'
    | '/adminpanel/team'
    | '/blog-details/$id'
    | '/team-details/$id'
    | '/admin/'
    | '/adminpanel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/blog-details'
    | '/contact'
    | '/license'
    | '/login'
    | '/project-details'
    | '/projects'
    | '/services'
    | '/team'
    | '/team-details'
    | '/admin/blog'
    | '/admin/projects'
    | '/admin/team'
    | '/adminpanel/blog'
    | '/adminpanel/projects'
    | '/adminpanel/team'
    | '/blog-details/$id'
    | '/team-details/$id'
    | '/admin'
    | '/adminpanel'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/adminpanel'
    | '/blog'
    | '/blog-details'
    | '/contact'
    | '/license'
    | '/login'
    | '/project-details'
    | '/projects'
    | '/services'
    | '/team'
    | '/team-details'
    | '/admin/blog'
    | '/admin/projects'
    | '/admin/team'
    | '/adminpanel/blog'
    | '/adminpanel/projects'
    | '/adminpanel/team'
    | '/blog-details/$id'
    | '/team-details/$id'
    | '/admin/'
    | '/adminpanel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminpanelRoute: typeof AdminpanelRouteWithChildren
  BlogRoute: typeof BlogRoute
  BlogDetailsRoute: typeof BlogDetailsRouteWithChildren
  ContactRoute: typeof ContactRoute
  LicenseRoute: typeof LicenseRoute
  LoginRoute: typeof LoginRoute
  ProjectDetailsRoute: typeof ProjectDetailsRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TeamDetailsRoute: typeof TeamDetailsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpanel': {
      id: '/adminpanel'
      path: '/adminpanel'
      fullPath: '/adminpanel'
      preLoaderRoute: typeof AdminpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-details': {
      id: '/blog-details'
      path: '/blog-details'
      fullPath: '/blog-details'
      preLoaderRoute: typeof BlogDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-details': {
      id: '/project-details'
      path: '/project-details'
      fullPath: '/project-details'
      preLoaderRoute: typeof ProjectDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-details': {
      id: '/team-details'
      path: '/team-details'
      fullPath: '/team-details'
      preLoaderRoute: typeof TeamDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/adminpanel/': {
      id: '/adminpanel/'
      path: '/'
      fullPath: '/adminpanel/'
      preLoaderRoute: typeof AdminpanelIndexRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/blog': {
      id: '/adminpanel/blog'
      path: '/blog'
      fullPath: '/adminpanel/blog'
      preLoaderRoute: typeof AdminpanelBlogRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/projects': {
      id: '/adminpanel/projects'
      path: '/projects'
      fullPath: '/adminpanel/projects'
      preLoaderRoute: typeof AdminpanelProjectsRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/adminpanel/team': {
      id: '/adminpanel/team'
      path: '/team'
      fullPath: '/adminpanel/team'
      preLoaderRoute: typeof AdminpanelTeamRouteImport
      parentRoute: typeof AdminpanelRoute
    }
    '/blog-details/$id': {
      id: '/blog-details/$id'
      path: '/$id'
      fullPath: '/blog-details/$id'
      preLoaderRoute: typeof BlogDetailsIdRouteImport
      parentRoute: typeof BlogDetailsRoute
    }
    '/team-details/$id': {
      id: '/team-details/$id'
      path: '/$id'
      fullPath: '/team-details/$id'
      preLoaderRoute: typeof TeamDetailsIdRouteImport
      parentRoute: typeof TeamDetailsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdminpanelRouteChildren {
  AdminpanelBlogRoute: typeof AdminpanelBlogRoute
  AdminpanelProjectsRoute: typeof AdminpanelProjectsRoute
  AdminpanelTeamRoute: typeof AdminpanelTeamRoute
  AdminpanelIndexRoute: typeof AdminpanelIndexRoute
}

const AdminpanelRouteChildren: AdminpanelRouteChildren = {
  AdminpanelBlogRoute: AdminpanelBlogRoute,
  AdminpanelProjectsRoute: AdminpanelProjectsRoute,
  AdminpanelTeamRoute: AdminpanelTeamRoute,
  AdminpanelIndexRoute: AdminpanelIndexRoute,
}

const AdminpanelRouteWithChildren = AdminpanelRoute._addFileChildren(
  AdminpanelRouteChildren,
)

interface BlogDetailsRouteChildren {
  BlogDetailsIdRoute: typeof BlogDetailsIdRoute
}

const BlogDetailsRouteChildren: BlogDetailsRouteChildren = {
  BlogDetailsIdRoute: BlogDetailsIdRoute,
}

const BlogDetailsRouteWithChildren = BlogDetailsRoute._addFileChildren(
  BlogDetailsRouteChildren,
)

interface TeamDetailsRouteChildren {
  TeamDetailsIdRoute: typeof TeamDetailsIdRoute
}

const TeamDetailsRouteChildren: TeamDetailsRouteChildren = {
  TeamDetailsIdRoute: TeamDetailsIdRoute,
}

const TeamDetailsRouteWithChildren = TeamDetailsRoute._addFileChildren(
  TeamDetailsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminpanelRoute: AdminpanelRouteWithChildren,
  BlogRoute: BlogRoute,
  BlogDetailsRoute: BlogDetailsRouteWithChildren,
  ContactRoute: ContactRoute,
  LicenseRoute: LicenseRoute,
  LoginRoute: LoginRoute,
  ProjectDetailsRoute: ProjectDetailsRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TeamDetailsRoute: TeamDetailsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
